---
all:
  children:
    application_servers:
      hosts:
        svlazext:
          ansible_host: svlazext
          ansible_connection: local
          ansible_user: ansible
          ansible_become: true
    development_servers:
      hosts:
        svlazdev:
          ansible_host: svlazdev
          ansible_connection: local
          ansible_user: ansible
          ansible_become: true
    dmz_servers:
      hosts:
        svlazextpub:
          ansible_host: svlazextpub
          ansible_connection: local
          ansible_user: ansible
          ansible_become: true
