---
all:
  children:
    application_servers:
      hosts:
        svlazext:
          ansible_host: svlazext
          ansible_connection: local
          ansible_user: ansible
          ansible_become: true
    development_servers:
      hosts:
        svldev:
          ansible_host: svldev
          ansible_connection: local
          ansible_user: ansible
          ansible_become: true
    docker_servers:
      children:
        application_servers:
        development_servers:
