---
# Tasks for Cron Jobs role

- name: Ensure cron is installed
  ansible.builtin.apt:
    name: cron
    state: present
  register: cron_apt_result
  retries: 10
  delay: 30
  until: cron_apt_result is succeeded
  tags: [cron_jobs]

- name: Configure cron jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute | default('0') }}"
    hour: "{{ item.hour | default('0') }}"
    day: "{{ item.day | default('*') }}"
    month: "{{ item.month | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    job: "{{ item.job }}"
    user: "{{ item.user | default(ansible_user) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ cron_jobs }}"
  tags: [cron_jobs]
