---
# Tasks for Git Repos role

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  register: git_apt_result
  retries: 10
  delay: 30
  until: git_apt_result is succeeded
  tags: [git_repos]

- name: Create git repository shims (single-repo format)
  ansible.builtin.include_tasks: clone_shim.yml
  loop: "{{ git_repos | selectattr('repo', 'defined') | list }}"
  loop_control:
    loop_var: shim_item
    label: "{{ shim_item.repo }}"
  vars:
    shim_repo: "{{ shim_item.repo }}"
    shim_dest: "{{ shim_item.dest }}"
    shim_version: "{{ shim_item.version | default('HEAD') }}"
    shim_owner: "{{ shim_item.user | default(ansible_user) }}"
    shim_group: "{{ shim_item.group | default(shim_item.user | default(ansible_user)) }}"
  tags: [git_repos]

- name: Create git repository shims (multi-repo format)
  ansible.builtin.include_tasks: clone_shim.yml
  loop: "{{ git_repos | selectattr('repos', 'defined') | list |
    subelements('repos') }}"
  loop_control:
    loop_var: shim_item
    label: "{{ shim_item.1 }}"
  vars:
    shim_repo: "{{ shim_item.1 }}"
    shim_dest: "{{ shim_item.0.dest }}/{{ shim_item.1 | basename }}"
    shim_version: "{{ shim_item.0.version | default('HEAD') }}"
    shim_owner: "{{ shim_item.0.user | default(ansible_user) }}"
    shim_group: "{{ shim_item.0.group | default(shim_item.0.user | default(ansible_user)) }}"
  tags: [git_repos]

- name: Synchronise repositories for GitHub users
  ansible.builtin.include_tasks: github_user.yml
  loop: "{{ git_repos | selectattr('github_user', 'defined') | list }}"
  loop_control:
    loop_var: git_repos_entry
    label: "{{ git_repos_entry.github_user }}"
  tags: [git_repos]
